name: AnonfilesUpload  
on:
  
  workflow_dispatch:
    inputs:
      Directlink:
        description: 'Enter DirectLink To Download âš¡ï¸'
        required: true
      Filename:
        description: 'Enter FIle nameðŸ‘ï¸â€ðŸ—¨ï¸ '
        required: true
      Token: 
         description: 'Brah add your TOKENðŸ‘½'
         required: true
           
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Directlink
        run: wget ${{ github.event.inputs.Directlink }}

      - name: Upload 
        run: |
         
         echo "Downloading the file and Uploading to 3 Different servers"
            sleep 3
             sudo apt install jq -y
             curl -F "file=@${{ github.event.inputs.Filename }}" https://api.anonfiles.com/upload?token=${{ github.event.inputs.Token }} >>outputs.txt
             cat outputs.txt | jq
             sleep 4
             
             curl -F "file=@${{ github.event.inputs.Filename }}" https://api.letsupload.cc/upload >>outputs1.txt
             cat outputs1.txt | jq
             
             sleep 4 
             
             curl -F "file=@${{ github.event.inputs.Filename }}" https://api.filechan.org/upload >>outputs2.txt
             
             cat outputs1.txt | jq
             
             sleep 3m
             

          
         
  
        
